### ISSUE TITLE
Minting ecash fails creating LN invoice with a 404 error

### ISSUE THREAD

**Issue by aphex3k** [cashubtc/cashu#115]
Web wallet fails to create invoice to mint ecash.

![image](https://user-images.githubusercontent.com/433270/222231815-f3dffcae-2818-424b-8087-f94803e1eb57.png)

The request fails in Chrome and Safari on iOS and Windows with a 404 error `{"detail":"Not Found"}`.

```
Request URL: https://legend.lnbits.com/mint?amount=1500
Request Method: GET
Status Code: 404 
Remote Address: 165.227.164.18:443
Referrer Policy: strict-origin-when-cross-origin
content-length: 22
content-type: application/json
date: Wed, 01 Mar 2023 18:29:57 GMT
server: Caddy
server: uvicorn
:authority: legend.lnbits.com
:method: GET
:path: /mint?amount=1500
:scheme: https
accept: application/json, text/plain, */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
referer: https://legend.lnbits.com/cashu/wallet
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
sec-gpc: 1
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
```

This does not happen on a self-hosted wallet.

**Comment by callebtc** [comment]
Hi, it seems like the mint URL is wrong. This URL `https://legend.lnbits.com/mint?amount=1500` does not point to a valid mint. Make sure to use the correct link (I don't know how you were able to add this mint in the first place). 

I know, it's still a bit confusing because of all the clients and the shared namespace but this issue would belong in this repo: https://github.com/lnbits/cashu

Closing because this is not a cashu-python issue
