### ISSUE TITLE
Bounty: Create a REST API for the Cashu Wallet Client

### ISSUE THREAD

**Issue by Altbierjupp** [cashubtc/cashu#39]
This Issue is to create a REST API for the Cashu Wallet Client for easier access of the functions included inside the wallet. The idea is to extend the wallet with an API to make it much easier to integrate in other applications and developments.

More details can be added inside this issue!

This is a Bounty offered by the [Nodesignal Podcast](https://twitter.com/nodesignal) and the developer who provide this functionality can get 250,000 Sats as Bounty. More Information about the Bounty program can be found here:
[https://nodesignal.space/spenden-bitcoin-bounties/](https://nodesignal.space/spenden-bitcoin-bounties/)

**Comment by callebtc** [comment]
## Bounty goals

The goal of this bounty is to extend the Cashu python [wallet](https://github.com/callebtc/cashu/tree/main/cashu/wallet) such that it can run in a `daemon` mode in the background and offer at least the same functionality as the CLI to a client REST API and thus to other applications running in the same network. We suspect that a successful execution of this idea will make it easier to build GUI wallet frontends around the Cashu wallet daemon since all token management and mint communication can be entirely left to the daemon and the wallet frontend can focus on UI and UX. 

In the best case and as a bonus, the submissions for this bounty could be bundled with a very simple example of a  Javascript UI packaged together with the Python wallet app such that both can be shipped to a user in the future.

The API integration should be executed via `uvicorn` and `FastApi` since those two frameworks are already used in Cashu.

Note: This description is a work-in-progress and could change a bit in the future.

**Comment by trbouma** [comment]
This is what I have so far. I have added the capability of managed wallets. app.anonsats.io

**Comment by callebtc** [comment]
Congratulations for the bounty @sihamon!
