### ISSUE TITLE
About the hash-to-curve algorithm

### ISSUE THREAD

**Issue by AdamISZ** [cashubtc/cashu#4]
Hi, thanks for this interesting work/repo!

In the hash-to-curve algorithm  you basically do:
1. Hash the message to an int
2. Try that int as an x coord, get a y coord
3. Try that (x,y) as a point, if fails, take the message as the str() cast of x, and go to 1.

My concern is mainly with step 2. of this algo. There are of course 2 valid y coords, but the function `compute_y` will return the one gotten by applying the Tonelli-Shanks algorithm here:

https://github.com/lc6chang/ecc-pycrypto/blob/fbe2d5b6846dd2ef1efb124c84dc83b91e77a579/ecc/math_utils/mod_sqrt.py#L4-L83

Afaict that process *is* deterministic, but it is a complicated multi-step algo and I would not be amazed if someone out there used a different implementation that gave N-x instead of x (i.e. the other valid square root).

Another detail that might be worth attending to is that `compute_y` returns 0 if there is no valid square root, and of course the `Point()` call will then fail, but it might be better to be somehow explicit about that, since the return value of '0' meaning 'fail' is sort of implementation specific.

But back to how to do the hash-to-point: I feel like it's a bit simpler and less potential for gotchas, to do it like:
1. Hash message and convert to int mod N
2. Try x as that int, if fails, append string "1" to message, then retry 1.
3. Continue retries as often as needed, appending "2", then "3" etc.

(Both this and your version are of course guaranteed to work computationally after a few tries by the 50% chance of success at each turn.)

**Comment by AdamISZ** [comment]
Hmm, on second thoughts I just realised that: because you're sticking with the `x` value and not some kind of `Point` representation, the fact that y might be different only affects the final outcome, not the intermediate steps. So perhaps there isn't a concern here, but ... I'll leave the issue here for now, just in case.

**Comment by phyro** [comment]
@AdamISZ thank you for taking a look into this. This is one of the reasons the first line of every file is a comment about my cryptographic background. I don't really understand the underlying math that creates the algebra on ECC so I can only think about it on a higher level which leaves me with "I can do algebra with these elements".
When I was implementing minicash, I didn't think anyone would find the project and use it so I picked the first library that supported simple operations on curves. After seeing cashu used this, I opened an issue to [replace the ECC lib with libsecp256k1](https://github.com/callebtc/cashu/issues/2) and rewrote the minicash implementation (on which this is based) to use libsecp256k1 from Bitcoin. The new code is here https://github.com/phyro/minicash which I believe is more relevant and likely much better to use. Both `secp.py` and `dhke.py` are relevant here, the hash_to_curve is now implemented as such https://github.com/phyro/minicash/blob/master/b_dhke.py#L38-L54.

I don't really know if my implementation is secure and would appreciate if anyone could take a look as I hope this gets used instead of the current library.

**Comment by AdamISZ** [comment]
> After seeing cashu used this, I opened an issue to https://github.com/callebtc/cashu/issues/2

Yep, saw that, agree with both points (at least, in general) that libsecp bindings are the way to go (as we use in Joinmarket for example), but also that there can be meaningful limitations with how much is exposed via the API.

> ... and rewrote the minicash implementation (on which this is based) to use libsecp256k1 from Bitcoin.

Great, thanks for the link, I'll try to find time to take a look.

(One more detail I just noticed: no need to use Tonelli-Shanks at all for secp256k1, since the prime is 3 mod 4, you can use the same thing mentioned in BIP340, c^((p-1)/4) as explained in note 10. But this comment may not be relevant considering the rest of the discussion.)

**Comment by phyro** [comment]
>Great, thanks for the link, I'll try to find time to take a look.

@AdamISZ sounds good! The libsecp changes were now added to the cashu project so they're available on both repos. If you find the time I suggest you check this repo to avoid jumping between minicash and cashu.

**Comment by AdamISZ** [comment]
Just to follow up on the now hash-to-*point* algorithm :)

Yeah this looks functionally more than fine but:

Here, you're encoding the hash output as hex:

https://github.com/callebtc/cashu/blob/414e07666ceda8d6d3c6bad80e0c70a4559f2575/core/b_dhke.py#L39

and then truncating to the first 33 bytes of the encoding. But, that means you take only 16 bytes of entropy when you could take 32. And in so doing, you would execute one less operation, too. i.e. you could do:

```
_hash = b"\x02" + hashlib.sha256(msg)
```

instead.

About the catch of `Exception` and the while loop, I mean it'd be pointless to quibble, but it's a shame the `secp256k1-py` library doesn't define an exception type specifically for pubkey deserialization failure, because if something else goes wrong in the code 'below' this while loop, you'll get stuck in an infinite loop there which is a bit icky. But yeah, that is just quibble, no need to worry.

(Re: only 16 bytes; 16 bytes or 128 bits is 'more than enough for anyone' a la Bill Gates, so it's hardly a risk that someone will be able to find preimages by brute force, which would indeed be a disaster because they could then mint coins by malleating existing coins).

**Comment by trbouma** [comment]
This is the IEET draft spec for hash_to_curve. It's being standardized for various signature schemes, so it is worth having a close look at to make sure it is consistent. It's a big document, and I don't even begin to say that I understand it all, but it might be useful to understand what the considerations and potential vulnerabilities might be.

https://datatracker.ietf.org/doc/draft-irtf-cfrg-hash-to-curve/

**Comment by callebtc** [comment]
I've been following this discussion closely and think we should at least follow @AdamISZ's [suggestion](https://github.com/callebtc/cashu/issues/4#issuecomment-1256906262) of the improved hash function in `hash_to_curve`. Obviously, this would break the validation of existing tokens which is why I started working on implementing [keysets](https://github.com/callebtc/cashu/pull/27) in Cashu which should help migrate old tokens to new ones by assigning each token an ID derived from the keyset it was signed with. 

That way, we can activate a new keyset later on that uses the new `hash_to_curve` and keep the old keyset alive for a bit to validate old tokens and migrate them to the newest keyset.

**Comment by callebtc** [comment]
This is the function we ended up with

```python
def hash_to_curve(message: bytes):
    """Generates a point from the message hash and checks if the point lies on the curve.
    If it does not, it tries computing a new point from the hash."""
    point = None
    msg_to_hash = message
    while point is None:
        try:
            _hash = hashlib.sha256(msg_to_hash).digest()
            point = PublicKey(b"\x02" + _hash, raw=True)
        except:
            msg_to_hash = _hash
    return point
```

**Comment by callebtc** [comment]
Closing until further discussions come up. Thank you everyone for participating.
